import random

NAME = "GTA6"
WIDTH = 1068
HEIGHT = 768
X_CENTRE = WIDTH / 2
Y_CENTRE = HEIGHT / 2
SEED = random.randrange(2147483647)

SPACE_ABOVE_PLAYER = 420
BRAKE_POWER = 2
FRICTION = 0.67 #px/s^2
MAX_SPEED = 420
MAX_TURN_SPEED = 420      # px/s
REVERSE_SPEED = -69
HANDLING = 5              # larger = snappier
AUTO_LANE_ALIGN = True
DEBUG = False
HITBOX = True
SPAWNCAMP_DELAY = 2000

TILE_SIZE_Y = 90
TILE_SIZE_X = 110
LINE_SIZE_Y = 90
LINE_SIZE_X = 10
ROAD_SIZE_X = (TILE_SIZE_X + LINE_SIZE_X) / 2
NUM_WEATHERING_PATTERNS = 8
NOT_BRITISH_DRIVING = False
TRAFFIC = 0.02